export const ACTION = Object.freeze({
    FETCH_OBJECT_INBOUND: 'FETCH_OBJECT_INBOUND',
    FETCH_OBJECT_OUTBOUND: 'FETCH_OBJECT_OUTBOUND',
    MODIFY_CURSOR: 'MODIFY_CURSOR',
    CREATE: 'CREATE',
    EXECUTE_LINK_ACTION_INBOUND: 'EXECUTE_LINK_ACTION_INBOUND',
    EXECUTE_LINK_ACTION_OUTBOUND: 'EXECUTE_LINK_ACTION_OUTBOUND',
    VERIFY_CURSOR: 'VERIFY_CURSOR',
    VALIDATE_INBOUND: 'VALIDATE_INBOUND',
    VALIDATE_OUTBOUND: 'VALIDATE_OUTBOUND',
    MODIFY_OBJECT: 'MODIFY_OBJECT',
    CLEANUP: 'CLEANUP'
});

export const DIRECTION = Object.freeze({
    INBOUND: 'INBOUND',
    OUTBOUND: 'OUTBOUND',

});

export const CONFIG_SHEET_NAME = 'config';
export const ERP_CONFIG = 'ERP_CONFIG';
export const SUCCESS = 'success';
export const FAIL = 'fail';
